import karelia
import time

def on_kill():
    """Define actions to be performed when the bot receives a !kill command"""
    print("Got killed :-(")

# Initialise a bot with nick (or [nick1, nick2]) and room the bot will connect to
bot = karelia.bot("ExampleBot", "test")

# Define response messages to the botrulez.
bot.stock_responses['short_help'] = "Short help message"
bot.stock_responses['long_help'] = ["Long help message can be sent over multiple messages","This message was generated by Example Bot"]

# Assign on_kill function to bot's on_kill.
bot.on_kill = on_kill

# Connect to the room
bot.connect()

while True:
    # Send a top-level messaage
    bot.send("/me has connected!")
    try:
        # Pick up a new packet from the heim servers. Note: is blocking.
        packet = bot.parse()

        if packet.type == "send-event":
            # Send a reply to the most recently processed message
            bot.reply(f"Hi {packet.data.sender.name}!")
            bot.log(event = f"Greeted {packet.data.sender.name}\n")

    except:
        bot.log()
        bot.disconnect()
    finally:
        time.sleep(10)
        bot.connect()
